### ISSUE TITLE
This really isn't the solution to the problem

### ISSUE THREAD

**Issue by fiddyspence** [MagePsycho/nginx-virtual-host-bash-script#1]
Doing this in bash, rather than an automation framework (Puppet, Ansible, Chef etc) really doesn't fix the problem.

What you need is something that translates from your developer environment all the way from development to actually running whatever it was you wanted nginx to do in your revenue facing systems.

Perfectly reasonable bash on the face of it, but not everything needs hitting really hard with shell.

**Comment by MagePsycho** [comment]
This is intended for development where you have lots of development domains as per application.
And using Ansible or other similar tools just to create virtual-host is an overkill.
